# print a triangle of stars:-

rows = 6
print('**********')
print('*********')
print('********')
print('*******')
print('******')
print('*****')
print('****')
print('***')
print('**')
print('*')
print('**********')
print('*********')
print('********')
print('*******')
print('******')
print('*****')
print('****')
print('***')
print('**')
print('*' '**********')
print('*********')
print('********')
print('*******')
print('******')
print('*****')
print('****')
print('***')
print('**')
print('*')
